- name: deploying a java web application
  hosts: target
  become: true 
  tasks:
    - name: copying the path
      copy:
         src: ./target/ROOT.war
         dest: /home/Amulya_Ravula/opt/tomcat/webapps/ROOT.war
